spring.config.activate.on-profile: docker

spring.datasource.username: root
spring.datasource.password: abcdefgh
spring.datasource.driver-class-name: com.mysql.cj.jdbc.Driver
spring.datasource.url: jdbc:mysql://docker-mysql:3306/school?createDatabaseIfNotExist=true

---
spring.config.activate.on-profile: localhost


spring.datasource.username: root
spring.datasource.password: abcdefgh
spring.datasource.driver-class-name: com.mysql.cj.jdbc.Driver
spring.datasource.url: jdbc:mysql://localhost:3306/school?createDatabaseIfNotExist=true