version: "3.3"
services:
  #MYSQL Container
  mysql:
    image: mysql:8
    container_name: docker-mysql
    volumes:
    - ./sql-init/:/docker-entrypoint-initdb.d/
    restart: always
    expose:
    - 3306
    environment:
      MYSQL_ROOT_PASSWORD: abcdefgh
    command: --default-authentication-plugin=mysql_native_password
  #Backend Container
  backend:
    image: maven:3.6.3-jdk-11
    container_name: docker-microservice-be
    working_dir: /usr/app/
    depends_on:
      - mysql
    volumes:
        - ../microservice-docker-be/:/usr/app
    expose: 
      - 8080
    command: mvn spring-boot:run
  #Frontend Container
  frontend:
    image: node:lts
    container_name: docker-microservice-fe
    expose:
      - 4200
    ports:
      - 4200:4200
    working_dir: /app
    depends_on:
      - backend
    volumes:
        - ../microservice-docker-fe/angular-app-student-fe/:/app/
    command: bash -c "npm install && npm install -g @angular/cli > /dev/null && ng serve --host 0.0.0.0 --port 4200 "
