version: "3.3"
networks:
  school-application-stack:
services:
  #MYSQL Container
  mysql:
    image: mysql:8
    container_name: docker-mysql
    volumes:
      - ./sql-init/:/docker-entrypoint-initdb.d/
    restart: always
    networks: 
      - school-application-stack
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    command: --default-authentication-plugin=mysql_native_password
  #Backend Container
  backend:
    image: maven:3.6.3-jdk-11
    container_name: docker-microservice-be
    working_dir: /usr/app/
    networks: 
      - school-application-stack
    volumes:
      - ${BACKEND_DIRECTORY}:/usr/app
    expose: 
      - ${BACKEND_PORT}
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    command:  ${BACKEND_COMMAND}
  #Frontend Container
  frontend:
    image: node:lts
    container_name: docker-microservice-fe
    working_dir: /app 
    networks: 
      - school-application-stack
    expose:
      - ${UI_PORT}
    ports:
      - ${UI_PORT}:${UI_PORT}
    volumes:
        - ${UI_DIRECTORY}:/app/
    command: ${UI_COMMAND}
