version: '3.1'
services:
  mysql:
    image: mysql:8
    container_name: localhost-mysql
    volumes:
    - ./sql-init/:/docker-entrypoint-initdb.d/
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    expose:
    - 3306
    environment:
      MYSQL_ROOT_PASSWORD: abcdefgh
    ports:
    - 3306:3306
  frontend:
    image: angular-development:1.0
    container_name: docker-microservice-fe
    ports:
      - 4200:4200
    volumes:
        - ../../microservice-docker-fe/angular-app-student-fe/:/app/
  backend:
    image: openjdk:11
    container_name: docker-microservice-be
    hostname: java_runner
    volumes:
        - ../../microservice-docker-be/target/microservice-docker-be-0.0.1-SNAPSHOT.jar:/usr/app/backend.jar
    working_dir: /usr/app/
    ports:
        - 8080:8080
        - 5005:5005
    command: java -jar -Xdebug -Xrunjdwp:transport=dt_socket,address=5005,server=y,suspend=n backend.jar --server.port=${serverport}
    depends_on:
        - samba 